Revert "port all output to QCDebug/QCWarning"
This reverts commit f0bdf7963d7e41e390e5a736ac63b6cb9888d522.

This broke the build for me and on CI:
/home/jenkins/sources/plasma-framework/kf5-qt5/src/declarativeimports/core/datamodel.cpp:214:9:
error: 'LOG_PLASMACORE' was not declared in this scope

CCMAIL:notmart@gmail.com