-require cmake 2.8.11
plasma-frameworks doesn't seem to build with 2.8.10.1:
qt5/include/QtCore/qglobal.h:975:4: error: #error "You must build your code with position independent code if Qt was built with -reduce-relocations. " "Compile your code with -fPIC or -fPIE."

This is most probably related to all the target-property related work from Stephen in CMake 2.8.11.

Alex